# Generated by Django 5.1.5 on 2025-02-04 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=20)),
                ('attribute_value', models.PositiveSmallIntegerField(default=10)),
                ('attribute_adjustment', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_armor_class', models.PositiveSmallIntegerField(default=10)),
                ('character_hit_points', models.PositiveSmallIntegerField(default=10)),
                ('character_movement_speed', models.PositiveSmallIntegerField(default=30)),
                ('character_is_inspired', models.BooleanField(default=False)),
                ('character_name', models.CharField(max_length=50)),
                ('character_class', models.CharField(max_length=50)),
                ('character_race', models.CharField(max_length=50)),
                ('character_background', models.CharField(max_length=50)),
                ('character_subclass', models.CharField(max_length=50)),
                ('character_level', models.PositiveSmallIntegerField(default=3)),
                ('character_conditions', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SavingThrowProficiencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saving_throw_name', models.CharField(max_length=20)),
                ('saving_throw_adjustment', models.PositiveSmallIntegerField(default=0)),
                ('saving_throw_is_proficient', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=20)),
                ('skill_adjustment', models.PositiveSmallIntegerField(default=0)),
                ('skill_is_proficient', models.BooleanField(default=False)),
                ('skill_is_expertise', models.BooleanField(default=False)),
            ],
        ),
    ]
